# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66cc7b0348342414ceb492ab052fc09a61ede22fd51560bac880bffbec3e5f0911b82575e5f3a44e23c6cc873ec678c1d1d1343fb5a8b0ed90294a72d592a843

test:
  secret_key_base: 72f7032fad382717fd9f2ca4e806240f6b795154f42642ee5473412f8f03c67845003facf09fa1557a1ec6db4e4f86e3cb9672d62beda34737f2a36f8bd7bf18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
